### ISSUE TITLE
.

### ISSUE THREAD

**Issue by BaHole** [ThibaultLatrille/AdaptaPop#1]
ModuleNotFoundError: No module named 'libraries'

**Comment by BaHole** [comment]
KeyError: 'ENSG'

**Comment by ThibaultLatrille** [comment]
Dear TongZhou Tao,
The error is due to the input file.
VCF file used as input for the script est_sfs.py requires several additional fields for the script to compute the ancestral allele,, specifically: "ENSG", "ENSG_POS", "STRAND", "SNP_TYPE", "OUTGROUP_1", "OUTGROUP_2", "OUTGROUP_3".
Actually this script is just a wrapper around EST-USFS (https://sourceforge.net/projects/est-usfs/, https://doi.org/10.1534/genetics.118.301120), I would recommend that you use EST-USFS directly for your specific analyses since my wrapper is primarily meant to be used inside the whole pipeline ;-)
